openapi: 3.0.0
info:
  title: Articolo API
  description: API per la gestione degli articoli
  version: 1.0.0

paths:
  /articoli:
    get:
      summary: Restituisce tutti gli articoli
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articolo'
        '404':
          description: Articoli non trovati
      tags:
        - Articoli

    post:
      summary: Crea un nuovo articolo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Articolo'
      responses:
        '201':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  createdArticolo:
                    $ref: '#/components/schemas/Articolo'
        '400':
          description: Richiesta non valida
      tags:
        - Articoli

  /articoli/{id}:
    get:
      summary: Restituisce un articolo specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articolo'
        '404':
          description: Articolo non trovato
      tags:
        - Articoli

    put:
      summary: Aggiorna un articolo specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Articolo'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articolo'
        '400':
          description: Richiesta non valida
      tags:
        - Articoli

    delete:
      summary: Elimina un articolo specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Articolo'
        '400':
          description: Richiesta non valida
      tags:
        - Articoli

  /articoli/filtered/{catalogo}:
    get:
      summary: Restituisce gli articoli filtrati per catalogo
      parameters:
        - in: path
          name: catalogo
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articolo'
        '404':
          description: La lista cataloghi è vuota
      tags:
        - Articoli

  /articoli/filtered/{catalogo}/queryBarcode/{barcode}:
    get:
      summary: Restituisce gli articoli filtrati per catalogo e barcode
      parameters:
        - in: path
          name: catalogo
          required: true
          schema:
            type: string
        - in: path
          name: barcode
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articolo'
        '404':
          description: La lista cataloghi è vuota
      tags:
        - Articoli

  /articoli/filtered/{catalogo}/queryNome/{nome}:
    get:
      summary: Restituisce gli articoli filtrati per catalogo e nome
      parameters:
        - in: path
          name: catalogo
          required: true
          schema:
            type: string
        - in: path
          name: nome
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Articolo'
        '404':
          description: La lista cataloghi è vuota
      tags:
        - Articoli

components:
  schemas:
    Articolo:
      type: object
      properties:
        nome:
          type: string
          required: true
        descrizione:
          type: string
        catalogo:
          type: string
        coloriDisponibili:
          type: array
          items:
            type: string
        taglieDisponibili:
          type: array
          items:
            type: string
        scontoApplicato:
          type: number
          default: 0
        prezzo:
          type: number
          required: true
        barCodes:
          type: array
          items:
            type: string
        status:
          type: boolean
          default: true
