openapi: 3.0.0
info:
  title: Documentazione API di Autenticazione
  version: 1.0.0
paths:
  /authenticate:
    post:
      summary: Autenticazione e ottenimento di un nuovo token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  description: Nome utente
                password:
                  type: string
                  description: Password dell'utente
      responses:
        '200':
          description: Autenticazione riuscita
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Stato dell'autenticazione
                    example: true
                  message:
                    type: string
                    description: Messaggio di successo
                    example: Enjoy your token!
                  token:
                    type: string
                    description: Token generato per l'autenticazione
                  username:
                    type: string
                    description: Nome utente
                  id:
                    type: string
                    description: ID dell'utente
                  self:
                    type: string
                    description: URL di auto-referenziazione
                    example: users/12345
        '401':
          description: Autenticazione fallita
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    description: Stato dell'autenticazione
                    example: false
                  message:
                    type: string
                    description: Messaggio di errore
                    example: Authentication failed. User or password not found.
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer

