openapi: 3.0.0
info:
  title: Autenticazione API
  description: API per l'autenticazione e generazione di token
  version: 1.0.0

paths:
  /authentications:
    post:
      summary: Autenticazione utente e generazione di un token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    default: true
                  message:
                    type: string
                  token:
                    type: string
                  username:
                    type: string
                  id:
                    type: string
                  self:
                    type: string
        '401':
          description: Autenticazione fallita
      tags:
        - Autenticazione

components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        password:
          type: string
        email:
          type: string
        _id:
          type: string
