openapi: 3.0.0
info:
  title: Gestione Aziende API
  description: API per la gestione delle aziende
  version: 1.0.0

paths:
  /aziende:
    get:
      summary: Recupera tutte le aziende
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Azienda'
        '404':
          description: Lista aziende vuota
      tags:
        - Aziende

    post:
      summary: Crea una nuova azienda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AziendaInput'
      responses:
        '201':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  createdAzienda:
                    $ref: '#/components/schemas/AziendaOutput'
        '400':
          description: Errore di validazione
      tags:
        - Aziende

    put:
      summary: Aggiorna tutte le aziende
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AziendaInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  nModified:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Aziende

    delete:
      summary: Elimina tutte le aziende
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Aziende

  /aziende/{id}:
    get:
      summary: Recupera un'azienda tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'azienda
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Azienda'
        '404':
          description: Azienda non trovata
      tags:
        - Aziende

    put:
      summary: Aggiorna un'azienda tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'azienda
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AziendaInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Azienda'
        '400':
          description: Errore di validazione
      tags:
        - Aziende

    delete:
      summary: Elimina un'azienda tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'azienda
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Azienda'
        '400':
          description: Errore di validazione
      tags:
        - Aziende

  /aziende/filtered/queryNome/{nome}:
    get:
      summary: Recupera le aziende filtrate per nome
      parameters:
        - in: path
          name: nome
          required: true
          schema:
            type: string
          description: Nome dell'azienda da cercare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Azienda'
        '404':
          description: Lista aziende filtrata vuota
      tags:
        - Aziende

components:
  schemas:
    Azienda:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        dati:
          type: object
        listaCataloghi:
          type: array
          items:
            type: string
        status:
          type: boolean
        dataInserimento:
          type: string
          format: date-time

    AziendaInput:
      type: object
      properties:
        nome:
          type: string
          required: true
        dati:
          type: object
        listaCataloghi:
          type: array
          items:
            type: string
        status:
          type: boolean

    AziendaOutput:
      type: object
      properties:
        risultato:
          $ref: '#/components/schemas/Azienda'
        request:
          type: object
          properties:
            type:
              type: string
            url:
              type: string

