openapi: 3.0.0
info:
  title: Gestione Cataloghi API
  description: API per la gestione dei cataloghi
  version: 1.0.0

paths:
  /cataloghi:
    get:
      summary: Recupera tutti i cataloghi
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Catalogo'
        '404':
          description: Lista cataloghi vuota
      tags:
        - Cataloghi

    post:
      summary: Crea un nuovo catalogo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogoInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  createdCatalogo:
                    $ref: '#/components/schemas/CatalogoOutput'
        '400':
          description: Errore di validazione
      tags:
        - Cataloghi

    put:
      summary: Aggiorna tutti i cataloghi
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogoInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  nModified:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Cataloghi

    delete:
      summary: Elimina tutti i cataloghi
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Cataloghi

  /cataloghi/{id}:
    get:
      summary: Recupera un catalogo tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del catalogo
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalogo'
        '404':
          description: Catalogo non trovato
      tags:
        - Cataloghi

    put:
      summary: Aggiorna un catalogo tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del catalogo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CatalogoInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalogo'
        '400':
          description: Errore di validazione
      tags:
        - Cataloghi

    delete:
      summary: Elimina un catalogo tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del catalogo
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Catalogo'
        '400':
          description: Errore di validazione
      tags:
        - Cataloghi

  /cataloghi/filtered/{azienda}:
    get:
      summary: Recupera i cataloghi filtrati per azienda
      parameters:
        - in: path
          name: azienda
          required: true
          schema:
            type: string
          description: Nome dell'azienda da filtrare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Catalogo'
        '404':
          description: Lista cataloghi filtrata vuota
      tags:
        - Cataloghi

  /cataloghi/filtered/{azienda}/queryNome/{nome}:
    get:
      summary: Recupera i cataloghi filtrati per azienda e nome
      parameters:
        - in: path
          name: azienda
          required: true
          schema:
            type: string
          description: Nome dell'azienda da filtrare
        - in: path
          name: nome
          required: true
          schema:
            type: string
          description: Nome del catalogo da cercare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Catalogo'
        '404':
          description: Lista cataloghi filtrata vuota
      tags:
        - Cataloghi

components:
  schemas:
    Catalogo:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        azienda:
          type: string
        status:
          type: boolean
        dataInserimento:
          type: string
          format: date-time

    CatalogoInput:
      type: object
      properties:
        nome:
          type: string
          required: true
        azienda:
          type: string
          required: true
        status:
          type: boolean

    CatalogoOutput:
      type: object
      properties:
        risultato:
          $ref: '#/components/schemas/Catalogo'
        request:
          type: object
          properties:
            type:
              type: string
            url:
              type: string
