openapi: 3.0.0
info:
  title: Gestione Dipendenti API
  description: API per la gestione dei dipendenti
  version: 1.0.0

paths:
  /dipendenti:
    get:
      summary: Recupera tutti i dipendenti
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dipendente'
        '404':
          description: Lista dipendenti vuota
      tags:
        - Dipendenti

    post:
      summary: Crea un nuovo dipendente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DipendenteInput'
      responses:
        '201':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  createdDipendente:
                    $ref: '#/components/schemas/DipendenteOutput'
        '400':
          description: Errore di validazione
      tags:
        - Dipendenti

    put:
      summary: Aggiorna tutti i dipendenti
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DipendenteInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  nModified:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Dipendenti

    delete:
      summary: Elimina tutti i dipendenti
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: number
                  ok:
                    type: number
        '400':
          description: Errore di validazione
      tags:
        - Dipendenti

  /dipendenti/{id}:
    get:
      summary: Recupera un dipendente tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del dipendente
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dipendente'
        '404':
          description: Dipendente non trovato
      tags:
        - Dipendenti

    put:
      summary: Aggiorna un dipendente tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del dipendente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DipendenteInput'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dipendente'
        '400':
          description: Errore di validazione
      tags:
        - Dipendenti

    delete:
      summary: Elimina un dipendente tramite ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID del dipendente
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dipendente'
        '400':
          description: Errore di validazione
      tags:
        - Dipendenti

  /dipendenti/filtered/queryNome/{nome}:
    get:
      summary: Recupera dipendenti filtrati per nome o cognome
      parameters:
        - in: path
          name: nome
          required: true
          schema:
            type: string
          description: Nome o cognome del dipendente da cercare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Dipendente'
        '404':
          description: Lista dipendenti filtrata vuota
      tags:
        - Dipendenti

components:
  schemas:
    Dipendente:
      type: object
      properties:
        _id:
          type: string
        nome:
          type: string
        cognome:
          type: string
        anagrafica:
          type: object
        status:
          type: boolean
        dataInserimento:
          type: string
          format: date-time

    DipendenteInput:
      type: object
      properties:
        nome:
          type: string
          required: true
        cognome:
          type: string
          required: true
        anagrafica:
          type: object
          required: true
        status:
          type: boolean

    DipendenteOutput:
      type: object
      properties:
        risultato:
          $ref: '#/components/schemas/Dipendente'
        request:
          type: object
          properties:
            type:
              type: string
            id:
              type: string
