openapi: 3.0.0
info:
  title: Gestione Ordini API
  description: API per la gestione degli ordini
  version: 1.0.0

paths:
  /ordini:
    get:
      summary: Ottieni tutti gli ordini
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ordine'
        '500':
          description: Errore durante la ricerca degli ordini
      tags:
        - Ordini

    post:
      summary: Crea un nuovo ordine
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdineRequest'
      responses:
        '201':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdineResponse'
        '400':
          description: Errore durante la creazione dell'ordine
      tags:
        - Ordini

    put:
      summary: Aggiorna tutti gli ordini
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrdineUpdateRequest'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: integer
                  nModified:
                    type: integer
                  ok:
                    type: integer
                  tags:
                    type: object
                required:
                  - n
                  - nModified
                  - ok
        '400':
          description: Errore durante l'aggiornamento degli ordini
      tags:
        - Ordini

    delete:
      summary: Elimina tutti gli ordini
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  n:
                    type: integer
                  ok:
                    type: integer
                  deletedCount:
                    type: integer
                required:
                  - n
                  - ok
                  - deletedCount
        '400':
          description: Errore durante l'eliminazione degli ordini
      tags:
        - Ordini

  /ordini/{id}:
    get:
      summary: Ottieni un ordine specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'ordine da recuperare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ordine'
        '404':
          description: Ordine non trovato
        '500':
          description: Errore durante la ricerca dell'ordine
      tags:
        - Ordini

    put:
      summary: Aggiorna un ordine specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'ordine da aggiornare
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/schemas/OrdineUpdateRequest'
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ordine'
        '400':
          description: Errore durante l'aggiornamento dell'ordine
        '404':
          description: Ordine non trovato
      tags:
        - Ordini

    delete:
      summary: Elimina un ordine specifico
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID dell'ordine da eliminare
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Ordine'
        '400':
          description: Errore durante l'eliminazione dell'ordine
        '404':
          description: Ordine non trovato
      tags:
        - Ordini

  /ordini/filteredByCliente/{cliente}:
    get:
      summary: Ottieni tutti gli ordini associati a un cliente
      parameters:
        - in: path
          name: cliente
          required: true
          schema:
            type: string
          description: ID del cliente
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ordine'
        '404':
          description: Ordini non trovati per il cliente specificato
        '500':
          description: Errore durante la ricerca degli ordini
      tags:
        - Ordini

  /ordini/filteredBySubagente/{subagente}:
    get:
      summary: Ottieni tutti gli ordini associati a un subagente
      parameters:
        - in: path
          name: subagente
          required: true
          schema:
            type: string
          description: ID del subagente
      responses:
        '200':
          description: Successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Ordine'
        '404':
          description: Ordini non trovati per il subagente specificato
        '500':
          description: Errore durante la ricerca degli ordini
      tags:
        - Ordini

components:
  schemas:
    Ordine:
      type: object
      properties:
        id:
          type: string
        cliente:
          type: string
        subagente:
          type: string
        listaArticoli:
          type: array
          items:
            type: object
        indirizzoSpedizione:
          type: object
        indirizzoFatturazione:
          type: object
        isEvaso:
          type: boolean
        status:
          type: boolean
        dataInserimento:
          type: string
          format: date-time

    OrdineRequest:
      type: object
      properties:
        cliente:
          type: string
        subagente:
          type: string
        listaArticoli:
          type: array
          items:
            type: object
        indirizzoSpedizione:
          type: object
        indirizzoFatturazione:
          type: object
      required:
        - cliente
        - subagente
        - listaArticoli

    OrdineUpdateRequest:
      type: object
      properties:
        cliente:
          type: string
        subagente:
          type: string
        listaArticoli:
          type: array
          items:
            type: object
        indirizzoSpedizione:
          type: object
        indirizzoFatturazione:
          type: object
        isEvaso:
          type: boolean
        status:
          type: boolean
      required:
        - cliente
        - subagente
        - listaArticoli
