openapi: 3.0.0
info:
  title: Documentazione API Subagenti
  description: Documentazione delle API per la gestione dei subagenti
  version: 1.0.0

paths:
  /subagenti:
    get:
      summary: Elenco dei subagenti
      responses:
        '200':
          description: Elenco dei subagenti recuperato con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subagent'
        '404':
          description: La lista dei subagenti è vuota
    post:
      summary: Creazione di un nuovo subagente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewSubagent'
      responses:
        '201':
          description: Subagente creato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateSubagentResponse'
        '400':
          description: Errore nella richiesta di creazione del subagente

  /subagenti/{id}:
    get:
      summary: Dettagli del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Dettagli del subagente recuperati con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subagent'
        '404':
          description: Il subagente richiesto non è stato trovato

    put:
      summary: Aggiornamento del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateSubagentRequest'
      responses:
        '200':
          description: Subagente aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subagent'
        '400':
          description: Errore nell'aggiornamento del subagente

    delete:
      summary: Eliminazione del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subagente eliminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subagent'
        '400':
          description: Errore nell'eliminazione del subagente

  /subagenti/filtered/queryNome/{nome}:
    get:
      summary: Filtraggio dei subagenti per nome/cognome
      parameters:
        - name: nome
          in: path
          description: Nome o cognome del subagente da cercare
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Subagenti filtrati recuperati con successo
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subagent'
        '404':
          description: La lista dei subagenti filtrati è vuota

  /subagenti/addCliente/{id}:
    put:
      summary: Aggiunta di un cliente alla lista del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddClientRequest'
      responses:
        '200':
          description: Cliente aggiunto con successo alla lista del subagente
        '400':
          description: Errore nell'aggiunta del cliente alla lista del subagente

  /subagenti/rimuoviCliente/{id}:
    put:
      summary: Rimozione di un cliente dalla lista del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveClientRequest'
      responses:
        '200':
          description: Cliente rimosso con successo dalla lista del subagente
        '400':
          description: Errore nella rimozione del cliente dalla lista del subagente

  /subagenti/addAzienda/{id}:
    put:
      summary: Aggiunta di un'azienda alla lista del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddCompanyRequest'
      responses:
        '200':
          description: Azienda aggiunta con successo alla lista del subagente
        '400':
          description: Errore nell'aggiunta dell'azienda alla lista del subagente

  /subagenti/rimuoviAzienda/{id}:
    put:
      summary: Rimozione di un'azienda dalla lista del subagente
      parameters:
        - name: id
          in: path
          description: ID del subagente
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RemoveCompanyRequest'
      responses:
        '200':
          description: Azienda rimossa con successo dalla lista del subagente
        '400':
          description: Errore nella rimozione dell'azienda dalla lista del subagente

components:
  schemas:
    Subagent:
      type: object
      properties:
        nome:
          type: string
          description: Nome del subagente
        cognome:
          type: string
          description: Cognome del subagente
        anagrafica:
          type: object
          description: Informazioni anagrafiche del subagente
        listaClienti:
          type: array
          items:
            type: string
          description: Lista dei clienti associati al subagente
        listaAziende:
          type: array
          items:
            type: string
          description: Lista delle aziende associate al subagente
        isAgente:
          type: boolean
          description: Indicatore se il subagente è un agente o meno
        status:
          type: boolean
          description: Stato attivo/inattivo del subagente
        dataInserimento:
          type: string
          format: date-time
          description: Data di inserimento del subagente

    NewSubagent:
      type: object
      properties:
        nome:
          type: string
          description: Nome del subagente
        cognome:
          type: string
          description: Cognome del subagente
        anagrafica:
          type: object
          description: Informazioni anagrafiche del subagente

    CreateSubagentResponse:
      type: object
      properties:
        message:
          type: string
          description: Messaggio di conferma
        createdsubagente:
          type: object
          properties:
            risultato:
              $ref: '#/components/schemas/Subagent'
            request:
              type: object
              properties:
                type:
                  type: string
                  description: Tipo di richiesta
                id:
                  type: string
                  description: ID del subagente creato

    UpdateSubagentRequest:
      type: object
      properties:
        nome:
          type: string
          description: Nuovo nome del subagente
        cognome:
          type: string
          description: Nuovo cognome del subagente
        anagrafica:
          type: object
          description: Nuove informazioni anagrafiche del subagente

    AddClientRequest:
      type: object
      properties:
        cliente:
          type: string
          description: ID del cliente da aggiungere alla lista del subagente

    RemoveClientRequest:
      type: object
      properties:
        cliente:
          type: string
          description: ID del cliente da rimuovere dalla lista del subagente

    AddCompanyRequest:
      type: object
      properties:
        azienda:
          type: string
          description: ID dell'azienda da aggiungere alla lista del subagente

    RemoveCompanyRequest:
      type: object
      properties:
        azienda:
          type: string
          description: ID dell'azienda da rimuovere dalla lista del subagente
