openapi: 3.0.0
info:
  title: Documentazione API Tecnici
  version: 1.0.0
paths:
  /tecnici:
    get:
      summary: Recupera tutti i tecnici
      responses:
        '200':
          description: Elenco dei tecnici
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tecnico'
        '404':
          description: Nessun tecnico trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Messaggio di errore
    post:
      summary: Crea un nuovo tecnico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TecnicoInput'
      responses:
        '200':
          description: Tecnico creato con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
                  createdTecnico:
                    $ref: '#/components/schemas/Tecnico'
    put:
      summary: Aggiorna tutti i tecnici
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TecnicoInput'
      responses:
        '200':
          description: Tecnici aggiornati con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
    delete:
      summary: Elimina tutti i tecnici
      responses:
        '200':
          description: Tecnici eliminati con successo
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Messaggio di successo
  /tecnici/{id}:
    get:
      summary: Recupera un tecnico specifico
      parameters:
        - in: path
          name: id
          description: ID del tecnico
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tecnico trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tecnico'
        '404':
          description: Tecnico non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Messaggio di errore
    put:
      summary: Aggiorna un tecnico specifico
      parameters:
        - in: path
          name: id
          description: ID del tecnico
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TecnicoInput'
      responses:
        '200':
          description: Tecnico aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tecnico'
        '404':
          description: Tecnico non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Messaggio di errore
    delete:
      summary: Elimina un tecnico specifico
      parameters:
        - in: path
          name: id
          description: ID del tecnico
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tecnico eliminato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tecnico'
        '404':
          description: Tecnico non trovato
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Messaggio di errore
components:
  schemas:
    Tecnico:
      type: object
      properties:
        _id:
          type: string
          description: ID del tecnico
        username:
          type: string
          description: Nome utente
        password:
          type: string
          description: Password del tecnico
        status:
          type: boolean
          description: Stato del tecnico
        loggedIn:
          type: boolean
          description: Flag di accesso
        isFirstAccess:
          type: boolean
          description: Flag del primo accesso
        codiceFiscale:
          type: string
          description: Codice fiscale del tecnico
        email:
          type: string
          description: Email del tecnico
    TecnicoInput:
      type: object
      properties:
        username:
          type: string
          description: Nome utente
          required: true
        password:
          type: string
          description: Password del tecnico
          required: true
        status:
          type: boolean
          description: Stato del tecnico
        loggedIn:
          type: boolean
          description: Flag di accesso
        isFirstAccess:
          type: boolean
          description: Flag del primo accesso
        codiceFiscale:
          type: string
          description: Codice fiscale del tecnico
          required: true
        email:
          type: string
          description: Email del tecnico
          required: true