openapi: 3.0.0
info:
  title: Documentazione API Tecnici
  version: 1.0.0
paths:
  /tecnici:
    get:
      summary: Recupera tutti i tecnici
      responses:
        '200':
          description: Elenco di tutti i tecnici
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tecnico'
        '404':
          description: La lista dei tecnici è vuota
        '500':
          description: Errore durante la ricerca dei tecnici
    post:
      summary: Inserisce un nuovo tecnico
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewTecnico'
      responses:
        '201':
          description: Tecnico inserito con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateTecnicoResponse'
        '400':
          description: Errore durante l'inserimento del tecnico
    put:
      summary: Aggiorna tutti i tecnici
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTecniciRequest'
      responses:
        '200':
          description: Tecnici aggiornati con successo
        '400':
          description: Errore durante l'aggiornamento dei tecnici
  '/tecnici/{id}':
    get:
      summary: Recupera un tecnico specifico
      parameters:
        - name: id
          in: path
          description: ID del tecnico
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tecnico trovato
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tecnico'
        '404':
          description: Tecnico non trovato
        '500':
          description: Errore durante la ricerca del tecnico
    put:
      summary: Aggiorna un tecnico specifico
      parameters:
        - name: id
          in: path
          description: ID del tecnico
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTecnicoRequest'
      responses:
        '200':
          description: Tecnico aggiornato con successo
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tecnico'
        '400':
          description: Errore durante l'aggiornamento del tecnico
    delete:
      summary: Elimina un tecnico specifico
      parameters:
        - name: id
          in: path
          description: ID del tecnico
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Tecnico eliminato con successo
        '400':
          description: Errore durante l'eliminazione del tecnico
components:
  schemas:
    Tecnico:
      type: object
      properties:
        codiceFiscale:
          type: string
          description: Codice fiscale del tecnico
        dataInserimento:
          type: string
          format: date-time
          description: Data di inserimento del tecnico
    NewTecnico:
      type: object
      properties:
        codiceFiscale:
          type: string
          description: Codice fiscale del nuovo tecnico
    CreateTecnicoResponse:
      type: object
      properties:
        message:
          type: string
          description: Messaggio di conferma
        createdTecnico:
          type: object
          properties:
            risultato:
              $ref: '#/components/schemas/Tecnico'
            request:
              type: object
              properties:
                type:
                  type: string
                  description: Tipo di richiesta
                url:
                  type: string
                  description: URL del tecnico creato
    UpdateTecniciRequest:
      type: object
      properties:
        codiceFiscale:
          type: string
          description: Nuovo codice fiscale per tutti i tecnici
    UpdateTecnicoRequest:
      type: object
      properties:
        codiceFiscale:
          type: string
          description: Nuovo codice fiscale per il tecnico
